# Generated by Django 2.2.14 on 2021-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_price2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price2',
        ),
        migrations.AddField(
            model_name='item',
            name='duration',
            field=models.CharField(choices=[('0', '15 Days'), ('1', '1 Month'), ('2', '3 Months')], default='0', max_length=1),
        ),
    ]
